VideoMVC/Controllers/ContratosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VideoMVC.Models;

namespace VideoMVC.Controllers
{
    public class ContratosController : Controller
    {
        private dbVideoMVCEntities db = new dbVideoMVCEntities();

        // GET: Contratos
        public ActionResult Index()
        {
            var tblContrato = db.tblContrato.Include(t => t.tblCliente);
            return View(tblContrato.ToList());
        }

        [HttpPost]
        public ActionResult Index(DateTime From, DateTime To)
        {
            var array = db.BuscarDato(From, To);
            return View(array);
        }

        // GET: Contratos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblContrato tblContrato = db.tblContrato.Find(id);
            if (tblContrato == null)
            {
                return HttpNotFound();
            }
            return View(tblContrato);
        }

        // GET: Contratos/Create
        public ActionResult Create()
        {
            ViewBag.idCliente = new SelectList(db.tblCliente, "idCliente", "nombreCliente");
            return View();
        }

        // POST: Contratos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idContrato,idCliente,montoContrato,fechaContrato")] tblContrato tblContrato)
        {
            if (ModelState.IsValid)
            {
                db.tblContrato.Add(tblContrato);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idCliente = new SelectList(db.tblCliente, "idCliente", "nombreCliente", tblContrato.idCliente);
            return View(tblContrato);
        }

        // GET: Contratos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblContrato tblContrato = db.tblContrato.Find(id);
            if (tblContrato == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCliente = new SelectList(db.tblCliente, "idCliente", "nombreCliente", tblContrato.idCliente);
            return View(tblContrato);
        }

        // POST: Contratos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idContrato,idCliente,montoContrato,fechaContrato")] tblContrato tblContrato)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblContrato).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idCliente = new SelectList(db.tblCliente, "idCliente", "nombreCliente", tblContrato.idCliente);
            return View(tblContrato);
        }

        // GET: Contratos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblContrato tblContrato = db.tblContrato.Find(id);
            if (tblContrato == null)
            {
                return HttpNotFound();
            }
            return View(tblContrato);
        }

        // POST: Contratos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblContrato tblContrato = db.tblContrato.Find(id);
            db.tblContrato.Remove(tblContrato);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VideoMVC/Views/Contratos/Create.cshtml
@model VideoMVC.Models.tblContrato

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblContrato</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idCliente, "idCliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.montoContrato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.montoContrato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.montoContrato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaContrato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaContrato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaContrato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

VideoMVC/Views/Contratos/Delete.cshtml
@model VideoMVC.Models.tblContrato

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblContrato</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.montoContrato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.montoContrato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaContrato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaContrato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblCliente.nombreCliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblCliente.nombreCliente)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VideoMVC/Views/Contratos/Details.cshtml
@model VideoMVC.Models.tblContrato

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tblContrato</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.montoContrato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.montoContrato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaContrato)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaContrato)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblCliente.nombreCliente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblCliente.nombreCliente)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idContrato }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VideoMVC/Views/Contratos/Edit.cshtml
@model VideoMVC.Models.tblContrato

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblContrato</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idContrato)

        <div class="form-group">
            @Html.LabelFor(model => model.idCliente, "idCliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.montoContrato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.montoContrato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.montoContrato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaContrato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaContrato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaContrato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

VideoMVC/Views/Contratos/Index.cshtml
@model IEnumerable<VideoMVC.Models.tblContrato>

@{
    ViewBag.Title = "Index";
}

<h2>Contratos Registrados</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

@using (Html.BeginForm("Index", "Contratos", FormMethod.Post))
{
    <label>Desde:&nbsp;</label><input type="date" name="From"  />
    <label>Hasta:&nbsp;</label><input type="date" name="To"  />
    <input type="submit" value="Buscar" />
}
<p></p>
<p>
    @Html.ActionLink("Mostrar todos", "Index")
</p>
<table class="table">
    <tr>
        <th>
            Cliente
        </th>
        <th>
            Monto
        </th>
        <th>
            Fecha
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tblCliente.nombreCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.montoContrato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaContrato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaContrato)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.idContrato }) |
                    @Html.ActionLink("Details", "Details", new { id = item.idContrato }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.idContrato })
                </td>*@
        </tr>
    }

</table>